name: last_bottle
description: "End Single Use Plastic"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame: ^1.15.0
  go_router: ^13.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.0
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/background/
    - assets/images/google_wallet/
