name: last_bottle
description: "End Single Use Plastic"
publish_to: "none"

version: 1.0.1+3

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame: ^1.15.0
  go_router: ^13.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  animate_gradient: ^0.0.2+1
  flutter_fortune_wheel: ^1.3.1
  logger: ^2.0.2+1
  flame_audio: ^2.1.8
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.0
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/audio/
    - assets/fonts/
    - assets/images/
    - assets/images/display/
    - assets/images/background/
    - assets/images/bottles/
    - assets/images/google_wallet/
    - assets/images/logo/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/Logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo/LogoTransparent.png"
  web:
    generate: true
    image_path: "assets/images/logo/LogoTransparentLg.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
